---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
{{- template "etcd-cluster-operator.labels" . }}
  name: {{ .Release.Name }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-leader-election-role
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
