apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: storageos-etcd-controller-manager
  namespace: storageos-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --proxy-url=storageos-proxy.storageos-etcd.svc
        command:
        - /manager
        env:
        - name: DISABLE_WEBHOOKS
          value: "true"
        image: storageos/etcd-cluster-operator-controller:develop
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: proxy
  name: storageos-etcd-proxy
  namespace: storageos-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: proxy
  template:
    metadata:
      labels:
        control-plane: proxy
    spec:
      containers:
      - args:
        - --api-port=8080
        image: storageos/etcd-cluster-operator-proxy:develop
        name: proxy
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      terminationGracePeriodSeconds: 10
