---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
{{- template "etcd-cluster-operator.labels" . }}
  name: {{ .Release.Name }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
