apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: proxy
  name: storageos-etcd-proxy
  namespace: storageos-etcd
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    control-plane: proxy
